### ISSUE TITLE
Configurable line width of output YAML

### ISSUE THREAD

**Issue by andriusvelykis** [emmanuelnk/github-actions-workflow-ts#13]
It would be good to expose configuration options for the underlying YAML generator, in particular the line width parameter. By default `js-yaml` sets the line width to 80, which uses a folded style for yaml via `>-` character. This impedes readability for strings (e.g. both expressions and `multilineString`). It would be good to be able to configure line width folding, or even disable (e.g. by setting line width to `-1`).

## Expected Behavior

Long strings are written as-is in a single/multi line, or folded at larger line width limit.

## Actual Behavior

Long strings are folded at 80 characters.

## Steps to Reproduce the Problem
  1. Use long string in e.g. an `if` expression or `run` multilineString.
  2. Generate workflow YAML

## Specifications
  - Version: 0.2.0
  - Platform: Mac
  
Very nice tool by the way!

**Comment by emmanuelnk** [comment]
Great suggestion. Let me see if I can add that to the config file.

**Comment by emmanuelnk** [comment]
This is now possible in v0.3.0.

Just create a `wac.config.json` file and use the `dumpOptions` property. e.g.
```json
{
  "dumpOptions": {
    "lineWidth": -1
  }
}
```
You can also add any of the other options as defined here: https://github.com/nodeca/js-yaml#dump-object---options-

Hope this helps. Thanks for the feedback.

Closing.
