### ISSUE TITLE
[Feature Request] zero-dependency library version

### ISSUE THREAD

**Issue by mrgrain** [emmanuelnk/github-actions-workflow-ts#15]
This looks awesome! I really like the API surface.

I think the current setup is great as a standalone tool, but not ideal for use in other packages.
For example in https://github.com/projen/projen we already have everything set up to generate YAML files from a JS object.
A zero-dependency library version of this package would make it easier to include in other tools.

## Current Behavior

The package is a CLI and library all-in-one tool.

As far as I can tell all its dependencies are used for the CLI only:
```
    "fast-glob": "^3.2.11",
    "js-yaml": "^4.1.0",
    "ts-node": "^10.8.1",
    "yargs": "^17.4.0"
```

## Expected Behavior

Publish a zero-dependency library version of this package that can be included in other projects.

Everything would work as before, but no files are created. Calling `Workflow.asObject()` will return the Workflow as an object that can than be manipulated further, and passed to any YAML tool and/or written to disk as desired.

```ts
 const exampleWorkflow = new Workflow('example-filename', { /***/ })
 exampleWorkflow.asObject();
```

**Comment by emmanuelnk** [comment]
Hi @mrgrain 
Sure let me look into it. I have been running some tests with projen so I guess this would fit in nicely as well. I'll try to knock it out on the weekend. 

Thanks for the feedback.

**Comment by kingpower2542** [comment]
Tigo Service @mrgrain 

>

**Comment by emmanuelnk** [comment]
This has been added in #26 via [github-actions-workflow-ts-lib](https://www.npmjs.com/package/github-actions-workflow-ts-lib) which is zero dependency version of this library.

In this scenario however, the object is obtained via
```ts
const exampleWorkflow = new Workflow('example-filename', { /***/ })

// workflow object
 exampleWorkflow.workflow;
```

I didn't see the need to add `asObject()` function as all it will be doing is `return this.workflow` but if this is behavior that projen needs to work with this lib I can do it. I am yet to try it out with projen hence why this is still a beta package. Once I do and I see everything works as expected I'll move it out of beta designation.
