### ISSUE TITLE
[Feature Request]: Provide a programatic API to generate the final YML

### ISSUE THREAD

**Issue by tusharmath** [emmanuelnk/github-actions-workflow-ts#25]
The CLI is a great experience but a programmatic API would be even better.

```ts
import * as fs from 'fs';

const mainWorkflow = new Workflow("CI", { ... });

const content = mainWorkflow.print(); // Should output String

fs.writeSync("./a.yml", content); 
```

This gives me a lot of flexiblity and control over how I generate my workflow files.

WDYT?

**Comment by emmanuelnk** [comment]
Great idea. This should be simple enough to implement.

**Comment by emmanuelnk** [comment]
Thinking some more about this, so far, the CLI has been responsible for generating YAML and that is where all the dependencies have been. In the core lib of this tool (which has the Workflow, Jobs, Step classes), there are no dependencies. This request would introduce a `js-yaml` dependency  into the `Workflow` class and would conflict with #15 which I do intend to implement as well.

My suggestion for you would be to extend the Workflow class in your own code using `js-yaml`:

```ts
import { Workflow as _Workflow, GeneratedWorkflowTypes } from 'github-actions-workflow-ts'
import * as jsYaml from 'js-yaml'

export class Workflow extends _Workflow {
	/**
	 * Convert the workflow to a YAML string.
	 * @param dumpOptions - Options for the YAML dump.
	 * @returns The YAML string representation of the workflow.
	 */
	toYamlString(dumpOptions?: jsYaml.DumpOptions): string {
		return jsYaml.dump(this.workflow, dumpOptions)
	}

	constructor(
		filename: string,
		workflowProps: Partial<GeneratedWorkflowTypes.Workflow>,
	) {
		super(filename, workflowProps)
	}
}

const mainWorkflow = new Workflow("CI", { ... });
const content = mainWorkflow.toYamlString({ noRefs: true }); // will output String

fs.writeSync("./a.yml", content); 
``` 

I understand its a little extra work but if you're going to do the work to write your own files, this isn't too big of a lift after the fact.
